name: C++ CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore SortingVisualizer.sln

    - name: Setup Vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'b81bc3a83fdbdffe80325eeabb2ec735a1f3c29d'

    - name: Integrate Vcpkg with MSBuild
      run: |
        .\vcpkg\vcpkg integrate install

    - name: Configure yaml-cpp with CMake
      run: |
        cmake -S external/yaml-cpp -B external/yaml-cpp/build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DYAML_BUILD_SHARED_LIBS=ON

    - name: Build yaml-cpp
      run: |
        cmake --build external/yaml-cpp/build --config Debug
        
    - name: Build solution
      run: msbuild SortingVisualizer.sln /p:Configuration=Debug

    - name: Run tests
      run: |
        .\x64\Debug\SortingTests.exe
